# Generated by Django 3.2.7 on 2021-10-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('ppic', models.ImageField(default='', upload_to='static/profile/')),
                ('pdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=80, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=100)),
                ('ppic', models.ImageField(default='', upload_to='static/profile/')),
                ('address', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='upcomingelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etitle', models.CharField(max_length=100)),
                ('edes', models.TextField(max_length=5000)),
                ('edate', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='uregister',
            fields=[
                ('uname', models.CharField(max_length=120)),
                ('ugender', models.CharField(max_length=10)),
                ('udob', models.DateField()),
                ('umobile', models.CharField(max_length=20)),
                ('uadhar', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('upasswd', models.CharField(max_length=50)),
                ('ustate', models.TextField(max_length=100)),
                ('ucity', models.TextField(max_length=100)),
                ('rdate', models.DateField()),
                ('upic', models.ImageField(default='', upload_to='static/profile/')),
            ],
        ),
    ]
