# Generated by Django 3.2.7 on 2021-10-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('aadhar', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=5000)),
                ('pdate', models.DateField()),
            ],
        ),
    ]
